### ISSUE TITLE
01 Welcome

### ISSUE THREAD

**Issue by bsiegel7** [CaroRob/docassemble-DeadBrokeDads#13]
01 Welcome
add space between bullets @carolrob

**Comment by CaroRob** [comment]
1. add css file dbd-styles.css to static folder
1. in dbd-styles.css,  define li
```
  li {
    padding-bottom: 1em;
  }
```
3. in features block in ChildSupportObligors.yml call css file
```
features:
  css: dbd-styles.css
```
