### ISSUE TITLE
dbd 03 - end date Does your most recent child support order have an end date?

### ISSUE THREAD

**Issue by bsiegel7** [CaroRob/docassemble-DeadBrokeDads#23]
dbd 03 - end date
Make radio buttons and add date or text field below radio button. 

4 options
end date
description of end
end date and description of end
nothing

We use this question to help establish if order is still current

need a follow - up question
you said the child support order ends, "..."
Has this happened yet?

**Comment by CaroRob** [comment]
Changed to keep 3 checkboxes, 
disable no end in child support order, if there is an end date, or there is a description of the end of child support. 
disable the others if there is no mention of ending child support in order.
